name = "https-www-supportflastdev-io-vn"
compatibility_date = "2024-09-23"
main = "infra/cloudflare/worker.js"

routes = [
  { pattern = "supportflastdev.io.vn/*", zone_name = "supportflastdev.io.vn" },
  { pattern = "www.supportflastdev.io.vn/*", zone_name = "supportflastdev.io.vn" }
]

[assets]
directory = "./supportflast_ui"
binding = "ASSETS"
