package config

import (
	"bufio"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"log"
	"math/big"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
)

var (
	loadOnce    sync.Once
	loadedEnvPath string
	loadedCount   int
)

// ResetForTest đặt lại trạng thái nạp file .env phục vụ các kịch bản kiểm thử độc lập
func ResetForTest() {
	loadOnce = sync.Once{}
	loadedEnvPath = ""
	loadedCount = 0
}

// InitEnv tự động kiểm tra, khởi tạo và nạp file '.env' vào môi trường tiến trình.
// 1. Nếu file '.env' chưa tồn tại, tự động sao chép từ '.env.example' (hoặc sinh cấu hình chuẩn)
//    và sinh JWT_SECRET, CLOUDPOOL_MASTER_KEY ngẫu nhiên độ phức tạp cao bằng CSPRNG.
// 2. Nạp toàn bộ các biến môi trường từ '.env' vào tiến trình mà không ghi đè biến hệ thống đã có.
// 3. Hoàn toàn sử dụng Go Standard Library, không phụ thuộc bất kỳ thư viện ngoài nào.
func InitEnv() error {
	var initErr error
	loadOnce.Do(func() {
		// 1. Tìm kiếm file .env sẵn có
		envPath := findEnvFile()

		// 2. Nếu chưa có file .env, tự động tạo từ .env.example hoặc sinh cấu hình chuẩn
		if envPath == "" {
			createdPath, err := autoGenerateEnv()
			if err != nil {
				log.Printf("[CONFIG] [ENV] [WARN] Không thể tự động tạo file '.env': %v", err)
			} else {
				envPath = createdPath
			}
		}

		// 3. Nếu tìm thấy hoặc vừa tạo thành công file .env, tiến hành nạp vào môi trường
		if envPath != "" {
			count, err := LoadEnvFile(envPath)
			if err != nil {
				log.Printf("[CONFIG] [ENV] [ERROR] Lỗi khi nạp file '%s': %v", envPath, err)
				initErr = err
				return
			}
			loadedEnvPath = envPath
			loadedCount = count

			envMode := Get("ENV", "production")
			port := Get("PORT", "8080")
			domain := Get("DOMAIN", "supportflastdev.io.vn")

			log.Printf("[CONFIG] [ENV] Đã nạp thành công %d biến môi trường từ file: '%s'", count, envPath)
			log.Printf("[CONFIG] [ENV] Thiết lập hoạt động: ENV=%s | PORT=%s | DOMAIN=%s", envMode, port, domain)
		} else {
			log.Println("[CONFIG] [ENV] [INFO] Không tìm thấy file '.env' hoặc '.env.example', sử dụng biến môi trường hệ thống mặc định.")
		}
	})
	return initErr
}

// GetLoadedEnvPath trả về đường dẫn file .env đã được nạp
func GetLoadedEnvPath() string {
	return loadedEnvPath
}

// GetLoadedCount trả về số lượng biến môi trường đã được nạp từ file .env
func GetLoadedCount() int {
	return loadedCount
}

// findEnvFile tìm file .env tại các vị trí ưu tiên
func findEnvFile() string {
	if custom := os.Getenv("ENV_FILE"); custom != "" {
		if fileExists(custom) {
			return custom
		}
		return ""
	}

	if customDir := os.Getenv("ENV_DIR"); customDir != "" {
		target := filepath.Join(customDir, ".env")
		if fileExists(target) {
			return target
		}
		return ""
	}

	candidates := []string{
		".env",
		filepath.Join("..", ".env"),
		filepath.Join("..", "..", ".env"),
		`f:\supportflast.dev\.env`,
	}

	// Thêm đường dẫn tương đối từ thư mục binary thực thi
	if exe, err := os.Executable(); err == nil {
		exeDir := filepath.Dir(exe)
		candidates = append(candidates,
			filepath.Join(exeDir, ".env"),
			filepath.Join(exeDir, "..", ".env"),
		)
	}

	for _, path := range candidates {
		if fileExists(path) {
			if abs, err := filepath.Abs(path); err == nil {
				return abs
			}
			return path
		}
	}
	return ""
}

// findExampleFile tìm file .env.example tại các vị trí ưu tiên
func findExampleFile() string {
	if custom := os.Getenv("ENV_EXAMPLE_FILE"); custom != "" {
		if fileExists(custom) {
			return custom
		}
		return ""
	}

	if customDir := os.Getenv("ENV_DIR"); customDir != "" {
		target := filepath.Join(customDir, ".env.example")
		if fileExists(target) {
			return target
		}
	}

	candidates := []string{
		".env.example",
		filepath.Join("..", ".env.example"),
		filepath.Join("..", "..", ".env.example"),
		`f:\supportflast.dev\.env.example`,
	}

	if exe, err := os.Executable(); err == nil {
		exeDir := filepath.Dir(exe)
		candidates = append(candidates,
			filepath.Join(exeDir, ".env.example"),
			filepath.Join(exeDir, "..", ".env.example"),
		)
	}

	for _, path := range candidates {
		if fileExists(path) {
			if abs, err := filepath.Abs(path); err == nil {
				return abs
			}
			return path
		}
	}
	return ""
}

// autoGenerateEnv cố gắng tạo file .env từ .env.example; nếu không có .env.example, tự động tạo .env mặc định
func autoGenerateEnv() (string, error) {
	if findExampleFile() != "" {
		if path, err := autoGenerateEnvFromExample(); err == nil {
			return path, nil
		}
	}
	return autoGenerateDefaultEnv()
}

// determineDefaultEnvDir xác định thư mục tối ưu để đặt file .env mặc định
func determineDefaultEnvDir() string {
	if custom := os.Getenv("ENV_DIR"); custom != "" {
		return custom
	}
	if currentDir, err := os.Getwd(); err == nil {
		if filepath.Base(currentDir) == "supportflast_engine" {
			parent := filepath.Dir(currentDir)
			return parent
		}
		return currentDir
	}
	return "."
}

// autoGenerateDefaultEnv tự động tạo file .env độc lập khi không có file .env.example
func autoGenerateDefaultEnv() (string, error) {
	randomJWTSecret, err := GenerateSecureHex(32)
	if err != nil {
		return "", fmt.Errorf("không thể sinh JWT secret ngẫu nhiên: %w", err)
	}

	randomMasterKey, err := GenerateSecureHex(16)
	if err != nil {
		return "", fmt.Errorf("không thể sinh CloudPool master key ngẫu nhiên: %w", err)
	}

	targetDir := determineDefaultEnvDir()
	targetEnvPath := filepath.Join(targetDir, ".env")

	defaultContent := fmt.Sprintf(`# ==============================================================================
# SUPPORTFLAST PLATFORM - CẤU HÌNH BIẾN MÔI TRƯỜNG (.env)
# Tự động sinh bởi Auto-Bootstrapping Engine
# Tên miền chính thức: supportflastdev.io.vn
# ==============================================================================

PORT=8080
HOST=0.0.0.0
DOMAIN=supportflastdev.io.vn
AI_ENGINE_URL=http://127.0.0.1:8000
AI_HOST=127.0.0.1
AI_PORT=8000

ENV=production
DATA_DIR=data
STORAGE_DIR=storage
UI_DIR=supportflast_ui
STATIC_DIR=supportflast_ui
JWT_KEYS_DIR=data/keys

ALLOWED_ORIGINS=https://supportflastdev.io.vn,http://localhost:8080,http://127.0.0.1:8080

JWT_SECRET=%s
ADMIN_USERNAME=admin
ADMIN_PASSWORD=Admin@2026!SupportFlast
JWT_EXPIRY_MINUTES=1440

CLOUDPOOL_MASTER_KEY=%s
OAUTH_REDIRECT_URL=https://supportflastdev.io.vn/api/accounts/oauth/callback
`, randomJWTSecret, randomMasterKey)

	if err := os.WriteFile(targetEnvPath, []byte(defaultContent), 0600); err != nil {
		return "", fmt.Errorf("không thể ghi file '%s': %w", targetEnvPath, err)
	}

	log.Printf("[CONFIG] [ENV] [AUTO-GEN] Phát hiện chưa có file '.env'. Đã tự động tạo mới '.env' tại: '%s'", targetEnvPath)
	log.Println("[CONFIG] [ENV] [AUTO-GEN] Đã cấu hình ADMIN_USERNAME='admin', mật khẩu Quản Trị Viên được bảo mật, và sinh JWT_SECRET (256-bit hex) ngẫu nhiên.")

	return targetEnvPath, nil
}

// autoGenerateEnvFromExample tự động sao chép file .env từ .env.example và sinh secret ngẫu nhiên
func autoGenerateEnvFromExample() (string, error) {
	examplePath := findExampleFile()
	if examplePath == "" {
		return "", fmt.Errorf("không tìm thấy file '.env.example' tại các đường dẫn dự án")
	}

	contentBytes, err := os.ReadFile(examplePath)
	if err != nil {
		return "", fmt.Errorf("không thể đọc file '%s': %w", examplePath, err)
	}
	content := string(contentBytes)

	// 1. Mật khẩu Quản Trị Viên khởi tạo chuẩn theo quy định hệ thống: Admin@2026!SupportFlast
	defaultAdminPass := "Admin@2026!SupportFlast"

	// 2. Sinh khóa bí mật JWT ngẫu nhiên (32 bytes entropy -> 64 ký tự hex)
	randomJWTSecret, err := GenerateSecureHex(32)
	if err != nil {
		return "", fmt.Errorf("không thể sinh JWT secret ngẫu nhiên: %w", err)
	}

	// 3. Sinh khóa bí mật CloudPool Master Key ngẫu nhiên (16 bytes -> 32 ký tự hex)
	randomMasterKey, _ := GenerateSecureHex(16)

	// 4. Thay thế các placeholder tương ứng trong nội dung
	content = replaceOrSetEnvLine(content, "ADMIN_USERNAME", "admin")
	content = replaceOrSetEnvLine(content, "ADMIN_PASSWORD", defaultAdminPass)
	content = replaceOrSetEnvLine(content, "JWT_SECRET", randomJWTSecret)
	if randomMasterKey != "" {
		content = replaceOrSetEnvLine(content, "CLOUDPOOL_MASTER_KEY", randomMasterKey)
	}

	// 5. Xác định vị trí lưu file .env (cùng thư mục với .env.example hoặc ENV_DIR nếu có)
	targetDir := filepath.Dir(examplePath)
	if customDir := os.Getenv("ENV_DIR"); customDir != "" {
		targetDir = customDir
	}
	targetEnvPath := filepath.Join(targetDir, ".env")

	// Ghi file với quyền 0600 (chỉ chủ sở hữu đọc/ghi an toàn theo Rule 3.2)
	if err := os.WriteFile(targetEnvPath, []byte(content), 0600); err != nil {
		return "", fmt.Errorf("không thể ghi file '%s': %w", targetEnvPath, err)
	}

	log.Printf("[CONFIG] [ENV] [AUTO-GEN] Phát hiện chưa có file '.env'. Đã tự động tạo mới '.env' từ '%s' tại: '%s'",
		filepath.Base(examplePath), targetEnvPath)
	log.Println("[CONFIG] [ENV] [AUTO-GEN] Đã cấu hình ADMIN_USERNAME='admin', mật khẩu Quản Trị Viên được bảo mật, và sinh JWT_SECRET (256-bit hex) ngẫu nhiên.")

	return targetEnvPath, nil
}

// replaceOrSetEnvLine thay thế giá trị của một KEY trong file .env hoặc thêm mới nếu chưa có
func replaceOrSetEnvLine(content, key, newValue string) string {
	lines := strings.Split(content, "\n")
	found := false
	prefix := key + "="

	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, prefix) {
			lines[i] = fmt.Sprintf("%s=%s", key, newValue)
			found = true
			break
		}
	}

	if !found {
		lines = append(lines, fmt.Sprintf("%s=%s", key, newValue))
	}
	return strings.Join(lines, "\n")
}

// LoadEnvFile đọc và phân tích cú pháp file .env, sau đó nạp vào môi trường tiến trình
func LoadEnvFile(envPath string) (int, error) {
	file, err := os.Open(envPath)
	if err != nil {
		return 0, err
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	lineNum := 0
	loadedCount := 0

	for scanner.Scan() {
		lineNum++
		line := scanner.Text()

		// Xóa Byte Order Mark (BOM UTF-8) nếu có ở dòng đầu tiên
		if lineNum == 1 {
			line = strings.TrimPrefix(line, "\xef\xbb\xbf")
		}

		line = strings.TrimSpace(line)

		// Bỏ qua dòng trống hoặc dòng chú thích bắt đầu bằng # hoặc ;
		if line == "" || strings.HasPrefix(line, "#") || strings.HasPrefix(line, ";") {
			continue
		}

		// Hỗ trợ cú pháp bash: 'export KEY=VALUE'
		if strings.HasPrefix(line, "export ") {
			line = strings.TrimSpace(strings.TrimPrefix(line, "export "))
		}

		// Tách theo dấu '=' đầu tiên
		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			continue
		}

		key := strings.TrimSpace(parts[0])
		val := strings.TrimSpace(parts[1])

		if key == "" {
			continue
		}

		// Xử lý giá trị có bao bọc bởi ngoặc kép "..." hoặc ngoặc đơn '...'
		if len(val) >= 2 {
			if strings.HasPrefix(val, "\"") && strings.HasSuffix(val, "\"") {
				val = val[1 : len(val)-1]
				val = unescapeDoubleQuotes(val)
			} else if strings.HasPrefix(val, "'") && strings.HasSuffix(val, "'") {
				val = val[1 : len(val)-1]
			} else {
				val = stripInlineComment(val)
			}
		} else {
			val = stripInlineComment(val)
		}

		// Chuẩn 12-factor: Chỉ gán nếu biến môi trường hệ thống chưa tồn tại
		// Giúp lập trình viên có thể ghi đè biến qua dòng lệnh (vd: PORT=9000 ./app)
		if os.Getenv(key) == "" {
			if err := os.Setenv(key, val); err == nil {
				loadedCount++
			}
		}
	}

	if err := scanner.Err(); err != nil {
		return loadedCount, err
	}

	return loadedCount, nil
}

// stripInlineComment loại bỏ chú thích inline sau giá trị không có ngoặc kép
func stripInlineComment(val string) string {
	if idx := strings.Index(val, " #"); idx != -1 {
		return strings.TrimSpace(val[:idx])
	}
	return val
}

// unescapeDoubleQuotes giải mã các ký tự escape trong chuỗi ngoặc kép
func unescapeDoubleQuotes(s string) string {
	s = strings.ReplaceAll(s, `\n`, "\n")
	s = strings.ReplaceAll(s, `\r`, "\r")
	s = strings.ReplaceAll(s, `\t`, "\t")
	s = strings.ReplaceAll(s, `\"`, `"`)
	s = strings.ReplaceAll(s, `\\`, `\`)
	return s
}

// GenerateSecurePassword sinh chuỗi mật khẩu mạnh ngẫu nhiên bằng CSPRNG
func GenerateSecurePassword(length int) (string, error) {
	if length < 16 {
		length = 16
	}

	const (
		upperChars   = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
		lowerChars   = "abcdefghijklmnopqrstuvwxyz"
		digitChars   = "0123456789"
		specialChars = "!@#$%^&*-_=+"
		allChars     = upperChars + lowerChars + digitChars + specialChars
	)

	// Đảm bảo có ít nhất 1 chữ hoa, 1 chữ thường, 1 số, 1 ký tự đặc biệt
	res := make([]byte, length)
	categories := []string{upperChars, lowerChars, digitChars, specialChars}

	for i, cat := range categories {
		idx, err := rand.Int(rand.Reader, big.NewInt(int64(len(cat))))
		if err != nil {
			return "", err
		}
		res[i] = cat[idx.Int64()]
	}

	// Điền các ký tự còn lại ngẫu nhiên từ toàn bộ bảng ký tự
	for i := len(categories); i < length; i++ {
		idx, err := rand.Int(rand.Reader, big.NewInt(int64(len(allChars))))
		if err != nil {
			return "", err
		}
		res[i] = allChars[idx.Int64()]
	}

	// Xáo trộn ngẫu nhiên (Fisher-Yates Shuffle) bằng CSPRNG
	for i := length - 1; i > 0; i-- {
		jBig, err := rand.Int(rand.Reader, big.NewInt(int64(i+1)))
		if err != nil {
			return "", err
		}
		j := int(jBig.Int64())
		res[i], res[j] = res[j], res[i]
	}

	return string(res), nil
}

// GenerateSecureHex sinh chuỗi hex ngẫu nhiên an toàn bằng CSPRNG
func GenerateSecureHex(byteLength int) (string, error) {
	if byteLength < 16 {
		byteLength = 16
	}
	bytes := make([]byte, byteLength)
	if _, err := rand.Read(bytes); err != nil {
		return "", err
	}
	return hex.EncodeToString(bytes), nil
}

// fileExists kiểm tra xem file có tồn tại và không phải thư mục
func fileExists(path string) bool {
	info, err := os.Stat(path)
	if err != nil {
		return false
	}
	return !info.IsDir()
}

// -----------------------------------------------------------------------------
// CÁC HÀM TIỆN ÍCH LẤY GIÁ TRỊ CẤU HÌNH (CONFIG HELPERS)
// -----------------------------------------------------------------------------

// Get lấy giá trị biến môi trường hoặc trả về giá trị mặc định nếu rỗng
func Get(key, defaultValue string) string {
	if val := strings.TrimSpace(os.Getenv(key)); val != "" {
		return val
	}
	return defaultValue
}

// GetInt lấy giá trị kiểu số nguyên hoặc trả về giá trị mặc định nếu lỗi/rỗng
func GetInt(key string, defaultValue int) int {
	valStr := strings.TrimSpace(os.Getenv(key))
	if valStr == "" {
		return defaultValue
	}
	val, err := strconv.Atoi(valStr)
	if err != nil {
		return defaultValue
	}
	return val
}

// GetBool lấy giá trị kiểu boolean hoặc trả về giá trị mặc định nếu lỗi/rỗng
func GetBool(key string, defaultValue bool) bool {
	valStr := strings.ToLower(strings.TrimSpace(os.Getenv(key)))
	if valStr == "" {
		return defaultValue
	}
	return valStr == "1" || valStr == "true" || valStr == "yes" || valStr == "on"
}

// IsProduction kiểm tra xem hệ thống có đang chạy ở chế độ production hay không
func IsProduction() bool {
	env := strings.ToLower(Get("ENV", "production"))
	return env == "production" || env == "prod"
}
